//! Compile the vendor catalog into the crate.
//!
//! Vendor names live in `captcha/kinds/*.toml` and nowhere else. This script
//! reads that directory at build time and emits a table, so no Rust source and
//! no engine source names a vendor, and adding a vendor is adding one file.
//!
//! The format is the one `captcha/kinds/_schema.toml` describes: flat scalars,
//! a `[signals]` table of string arrays, and a one-line inline `token` table.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    // `kinds` is the catalog directory: a symlink to `captcha/kinds` in the
    // tree, a real directory in the published crate, so the build input travels
    // with the package and there is still exactly one copy of the data.
    let kinds = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("kinds");
    println!("cargo:rerun-if-changed={}", kinds.display());

    let mut files: Vec<PathBuf> = std::fs::read_dir(&kinds)
        .unwrap_or_else(|e| panic!("read {}: {e}", kinds.display()))
        .filter_map(|entry| {
            let path = entry.expect("dir entry").path();
            let is_toml = path.extension().and_then(|s| s.to_str()) == Some("toml");
            let is_schema = path.file_name().and_then(|s| s.to_str()) == Some("_schema.toml");
            (is_toml && !is_schema).then_some(path)
        })
        .collect();
    files.sort();
    assert!(!files.is_empty(), "no vendor TOML in {}", kinds.display());

    let mut out = String::from("// Generated by build.rs from captcha/kinds/. Do not edit.\n");
    out.push_str("pub static CATALOG: &[VendorBinding] = &[\n");
    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let binding = parse(path);
        write_binding(&mut out, &binding, path);
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("catalog.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}

struct Binding {
    name: String,
    kind: String,
    /// Where the widget's actionable element lives, in chrome-visible language.
    /// The engine reads it; nothing here interprets it.
    target: String,
    signals: BTreeMap<String, Vec<String>>,
    token_inputs: Vec<String>,
    token_cookies: Vec<String>,
}

fn parse(path: &Path) -> Binding {
    let raw = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut name = String::new();
    let mut kind = String::new();
    let mut target = String::new();
    let mut signals: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut token_inputs = Vec::new();
    let mut token_cookies = Vec::new();
    let mut section = String::new();

    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line.starts_with('[') {
            section = line.trim_matches(&['[', ']'][..]).to_string();
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        let value = value.trim();
        // `name`, `kind`, `target`, and `token` are file-level keys wherever they
        // appear: the corpus writes them after `[signals]`, so keying on the
        // current section would file them under the wrong table.
        match (section.as_str(), key) {
            (_, "name") => name = unquote(value),
            (_, "kind") => kind = unquote(value),
            (_, "target") => target = unquote(value),
            (_, "token") => {
                for field in ["hidden_input", "verify_field"] {
                    if let Some(found) = inline_field(value, field) {
                        token_inputs.push(found);
                    }
                }
                if let Some(found) = inline_field(value, "cookie") {
                    token_cookies.push(found);
                }
            }
            ("signals", _) => {
                signals.insert(key.to_string(), array(value));
            }
            _ => {}
        }
    }
    assert!(!name.is_empty(), "{} has no name", path.display());
    assert!(!kind.is_empty(), "{} has no kind", path.display());
    Binding {
        name,
        kind,
        target,
        signals,
        token_inputs,
        token_cookies,
    }
}

fn unquote(value: &str) -> String {
    value.trim().trim_matches('"').replace("\\\"", "\"")
}

/// String array on one line or spread over several: the schema keeps arrays
/// short, so joining on the closing bracket is enough.
fn array(value: &str) -> Vec<String> {
    value
        .trim()
        .trim_start_matches('[')
        .trim_end_matches(']')
        .split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(unquote)
        .collect()
}

fn inline_field(value: &str, field: &str) -> Option<String> {
    let at = value.find(field)?;
    let rest = &value[at + field.len()..];
    let rest = rest.trim_start().strip_prefix('=')?.trim_start();
    let inner = rest.strip_prefix('"')?;
    let end = inner.find('"')?;
    Some(inner[..end].to_string())
}

fn write_binding(out: &mut String, binding: &Binding, path: &Path) {
    let empty = Vec::new();
    let list = |key: &str| -> String {
        let values = binding.signals.get(key).unwrap_or(&empty);
        let mut s = String::from("&[");
        for v in values {
            let _ = write!(s, "{:?}, ", v);
        }
        s.push(']');
        s
    };
    let strings = |values: &[String]| -> String {
        let mut s = String::from("&[");
        for v in values {
            let _ = write!(s, "{:?}, ", v);
        }
        s.push(']');
        s
    };
    let _ = writeln!(
        out,
        "    VendorBinding {{ name: {:?}, kind: {:?}, source: {:?}, target: {:?}, iframe_src: {}, custom_elements: {}, selectors: {}, cookies: {}, scripts: {}, token_inputs: {}, token_cookies: {} }},",
        binding.name,
        binding.kind,
        path.file_name().and_then(|s| s.to_str()).unwrap_or_default(),
        binding.target,
        list("iframe_src"),
        list("custom_elements"),
        list("selectors"),
        list("cookies"),
        list("scripts"),
        strings(&binding.token_inputs),
        strings(&binding.token_cookies),
    );
}
